# basic server setting
server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

# spring server setting
spring:
  # db setting
  datasource:
    url: jdbc:mysql://localhost:3306/photo
    username: jake
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa setting
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  # multipart setting
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB

  #security setting
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1213080049393733
            client-secret: 604f3e3885019d0497d27dc8181d5747
            scope:
              - public_profile
              - email

# file path
file:
  path: C:\Users\epike\Documents\projects\photogram\upload\